name: Deploy Ahoy
on:
  release:
    types:
      - released
  push:
    branches: [ main ]
concurrency: deployment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: shivammathur/setup-php@v2

        with:
          php-version: 8.4
          extensions: pdo_mysql
          coverage: none
          tools: composer:v2
      - run: composer install
      - run: rsync -rzcEl . root@159.65.145.67:/var/www/html --exclude-from=".rsyncignore" --checksum --delete