name: Deploy Ahoy
on:
  release:
    types:
      - released
  push:
    branches: [ main ]
concurrency: deployment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2

        with:
          php-version: 8.4
          extensions: pdo_mysql
          coverage: none
          tools: composer:v2
      - run: composer install
      - name: Add identity file Set up SSH agent with private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $HOME/deploy.key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PLATFORMSH_SSH_PRIVATE_KEY }} > $HOME/deploy.key
      - run: chmod 400 $HOME/deploy.key
      - run: mkdir -p $HOME/.ssh && touch $HOME/.ssh/known_hosts
      - name: keyscan
        run: |
          ssh-keyscan -H 159.65.145.67 >> $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/known_hosts
      # - run: rsync -e "ssh" -rzcEl . root@159.65.145.67:/var/www/html --exclude-from=".rsyncignore" --checksum --delete
      - run: rsync -e "ssh -i $HOME/deploy.key" -rzcEl . root@159.65.145.67:/var/www/html --exclude-from=".rsyncignore" --checksum --delete

      # - run: ssh root@159.65.145.67 ' /var/www/html/vendor/bin/drush updb --yes'
      # - run: ssh root@159.65.145.67 ' /var/www/html/vendor/bin/drush cim --yes'
      - name: Run Drush Deploy with sudo and cd
        run: |
          ssh -i $HOME/deploy.key root@159.65.145.67 'sudo bash -c "cd /var/www/html && /var/www/html/vendor/bin/drush deploy --yes -vvv"'